services:
  nginx:
    image: nginx:1.25.4-alpine3.18
    restart: always
    volumes:
      - epg-data:/usr/share/nginx/html/epg:ro
    ports:
      - 80:80
  gatotv:
    image: agarciadealba/epg
    command: ["npm", "run", "grab", "--", "--site=gatotv.com", "--output=epg/gatotv.xml", "--cron=0 6,18 * * *"]
    # command: ["sleep", "3600"]
    volumes:
      - epg-data:/home/node/app/epg:rw
    environment:
      NODE_ENV: production
  xumotv:
    image: agarciadealba/epg
    command: ["npm", "run", "grab", "--", "--site=xumo.tv", "--output=epg/xumotv.xml", "--cron=5 6,18 * * *"]
    volumes:
      - epg-data:/home/node/app/epg:rw
    environment:
      NODE_ENV: production
volumes:
  epg-data:
