services:
  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    volumes:
      - epg-data:/usr/share/nginx/html/epg:ro
    ports:
      - 80:80
  epg:
    image: agarciadealba/epg
    # command: ["npm", "run", "grab", "--", "--site=gatotv.com", "--output=epg/gatotv.xml", "--cron=*/5 * * * *"]
    command: ["sleep", "3600"]
    volumes:
      - epg-data:/home/node/app/epg
    environment:
      NODE_ENV: production
      # SITE_GATO: gatotv.com
      # SITE_DENS: dens.tv
volumes:
  epg-data: